### ISSUE TITLE
libzip 컴파일 문제가 발생합니다

### ISSUE THREAD

**Issue by hsccr** [hsccr/gtk-win32#2]
~~~
    GTK_DIR


-- Build files have been written to: C:/gtk-build/build/x64/debug/libzip
Scanning dependencies of target zip
[  0%] Building C object lib/CMakeFiles/zip.dir/zip_add.c.obj
zip_add.c
c:\msys64\mingw64\include\zconf.h(452) : fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
Traceback (most recent call last):
  File "build.py", line 1575, in build
    self.__build_one(p)
  File "build.py", line 1615, in __build_one
    proj.build()
  File "build.py", line 1115, in build
    self.exec_vs(r'nmake /nologo', add_path=self.builder.opts.cmake_path)
  File "build.py", line 121, in exec_vs
    self.builder.exec_vs(cmd, working_dir=self._get_working_dir(), add_path=add_path)
  File "build.py", line 1688, in exec_vs
    self.__execute(self.__sub_vars(cmd), working_dir=working_dir, add_path=add_path, env=self.vs_env)
  File "build.py", line 1720, in __execute
    subprocess.check_call(args, cwd=working_dir, env=env, shell=True)
  File "C:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'nmake /nologo' returned non-zero exit status 2
Error: libzip build failed

C:\gtk-build\github\gtk-win32>
~~~

**Comment by hsccr** [comment]
`C:\msys64\mingw64\include\zconf.h(411~413)`
~~~
#if 1    /* was set to #if 1 by ./configure */
#  define Z_HAVE_UNISTD_H
#endif
~~~
`to`
~~~
#if 0    /* was set to #if 1 by ./configure */
#  define Z_HAVE_UNISTD_H
#endif
~~~
